import Head from 'next/head'
// import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Tailwind Master</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen text-gray-900 bg-gray-100'>Home</div>
    </>
  )
}
