import Head from 'next/head'
// import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-gray-100 text-gray-900 h-screen'>Home</div>
    </div>
  )
}
